POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Great Person",
    "number": "05012345678"
}

###

GET http://localhost:3001/api/persons/

###

DELETE http://localhost:3001/api/persons/2