POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplcmUiLCJpZCI6IjY0ZDM2OWIyOTE0OTAzNjg2MGZjNTlhNyIsImlhdCI6MTY5MTU4MzQwNiwiZXhwIjoxNjkxNTg3MDA2fQ.Vff3EMXBfy_w7mvmT0YzedPQWPypuoOqYg2PVDbcSr4

{
    "username": "Jere",
    "title": "Poistuu pian",
    "author": "minä",
    "url": "asd.fi"
}

###
DELETE http://localhost:3003/api/blogs/64d383c5335fa0bb8277af68
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplcmUiLCJpZCI6IjY0ZDM2OWIyOTE0OTAzNjg2MGZjNTlhNyIsImlhdCI6MTY5MTU4MzQwNiwiZXhwIjoxNjkxNTg3MDA2fQ.Vff3EMXBfy_w7mvmT0YzedPQWPypuoOqYg2PVDbcSr4

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "strengv",
    "name": "Ville Strengell",
    "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Jere",
    "name": "Luukas",
    "password": "salasana"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Jere",
    "password": "salasana"
}