POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Uusi blogi",
    "author": "Ville",
    "url": "jee.com",
    "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/649acd9bcb3ef6a6b1a942ee