POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Pyyntöjen lähetys onnistuu VSCodesta REST Clientin avulla",
    "author": "Fiksu ucco",
    "url": "REST_client.com",
    "likes": 6
}

###

DELETE http://localhost:3003/api/blogs/64cb736758f72a16ce0369bb

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "strengv",
    "name": "Ville Strengell",
    "password": "salasana"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Jee",
    "name": "Luukas",
    "password": "sal"
}